#pragma checksum "MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "609BF4384D0A6BAC515E244D25B49B55C6017BDD49F9236F3C0B98E51DDF76B9"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using API2020;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace API2020 {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 11 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_CreateBeam;
        
        #line default
        #line hidden
        
        
        #line 12 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_CreatePlate;
        
        #line default
        #line hidden
        
        
        #line 13 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_CreateAssembly;
        
        #line default
        #line hidden
        
        
        #line 14 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_MoveWorkPlane;
        
        #line default
        #line hidden
        
        
        #line 15 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_CreteDetail;
        
        #line default
        #line hidden
        
        
        #line 16 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_CreateWeldAndBolts;
        
        #line default
        #line hidden
        
        
        #line 17 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_CreateDrawing;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/API2020;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_CreateBeam = ((System.Windows.Controls.Button)(target));
            
            #line 11 "MainWindow.xaml"
            this.btn_CreateBeam.Click += new System.Windows.RoutedEventHandler(this.btn_CreateBeam_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btn_CreatePlate = ((System.Windows.Controls.Button)(target));
            
            #line 12 "MainWindow.xaml"
            this.btn_CreatePlate.Click += new System.Windows.RoutedEventHandler(this.btn_CreatePlate_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btn_CreateAssembly = ((System.Windows.Controls.Button)(target));
            
            #line 13 "MainWindow.xaml"
            this.btn_CreateAssembly.Click += new System.Windows.RoutedEventHandler(this.btn_CreateAssembly_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btn_MoveWorkPlane = ((System.Windows.Controls.Button)(target));
            
            #line 14 "MainWindow.xaml"
            this.btn_MoveWorkPlane.Click += new System.Windows.RoutedEventHandler(this.btn_MoveWorkPlane_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btn_CreteDetail = ((System.Windows.Controls.Button)(target));
            
            #line 15 "MainWindow.xaml"
            this.btn_CreteDetail.Click += new System.Windows.RoutedEventHandler(this.btn_CreteDetail_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.btn_CreateWeldAndBolts = ((System.Windows.Controls.Button)(target));
            
            #line 16 "MainWindow.xaml"
            this.btn_CreateWeldAndBolts.Click += new System.Windows.RoutedEventHandler(this.btn_CreateWeldAndBolts_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.btn_CreateDrawing = ((System.Windows.Controls.Button)(target));
            
            #line 17 "MainWindow.xaml"
            this.btn_CreateDrawing.Click += new System.Windows.RoutedEventHandler(this.btn_CreateDrawing_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

